baseURL = "/"
languageCode = "zh-cn"
title = "站点名称"
theme = "focus-on-work"
googleAnalytics = "G-H2CXZ7F4CB"
enableRobotsTXT = true

[params]
	favicon = "/images/fav.svg"
	home_title = "Hi, I'am XXX"
	home_subtitle = "主标题"
	home_description = "主页详细信息"
	github = ""
	bilibili = ""
	blog = ""
	phone = "your_PhoneNumber"
	email = "your_Email"
	location = "your_Location"
	button = "去 联 系 我"
	home = "主页"
	work = "全部站点"
	about = "关于我"
	contact = "联系我"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true